- name: "Update package repository"
  ansible.builtin.apt: update_cache=yes

- name: "Install nginx dependencies"
  ansible.builtin.apt:
    name:
      - curl
      - gpgv
      - ca-certificates
      - lsb-release
      - ubuntu-keyring

- name: "install nginx"
  ansible.builtin.apt:
    name:
      - nginx
  # shell: /home/ansible/nginx-ansible/playbooks/roles/nginx/files/install_nginx.sh
   
