- name: Ubuntu Nginx Web Server
  hosts: nginx_hosts
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/main.yml
  vars:
    ansible_become_password: "{{ sudo_password }}"
  tasks:
    - name: "Install nginx"
      include_role:
        name: "nginx"
        tasks_from: "install_nginx.yml"

    - name: "Prepare static files"
      include_role:
        name: "nginx"
        tasks_from: "serve_web_content.yml"

    - name: "Configure and start server"
      include_role:
        name: "nginx"
        tasks_from: "configure_virtual_host.yml"